spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: yun7152!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
